// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using MilesL.BotherMeNot.Api.Models;
using System;

namespace MilesL.BotherMeNot.Api.Migrations
{
    [DbContext(typeof(BotherMeNotDbContext))]
    [Migration("20171007172646_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MilesL.BotherMeNot.Api.Models.Contact", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("MilesL.BotherMeNot.Api.Models.ContactAttempt", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Action");

                    b.Property<int?>("ContactId");

                    b.Property<DateTime?>("ContactTime");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactAttempt");
                });

            modelBuilder.Entity("MilesL.BotherMeNot.Api.Models.ContactAttempt", b =>
                {
                    b.HasOne("MilesL.BotherMeNot.Api.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
